// 사망 후 행정 처리 체크리스트 데이터
// 기준: 사망일로부터의 경과일
// ※ 일부 기한은 "사망일이 속한 달의 말일"이 기준점이므로 D-day 계산 시 주의

export const CATEGORIES = [
  { id: "immediate", label: "즉시 (1~3일)", color: "#ef4444" },
  { id: "week1", label: "1주 이내", color: "#f97316" },
  { id: "month1", label: "1개월 이내", color: "#eab308" },
  { id: "month3", label: "3개월 이내", color: "#3b82f6" },
  { id: "month6", label: "6개월 이내", color: "#8b5cf6" },
  { id: "after", label: "이후", color: "#6b7280" },
];

export const CHECKLIST = [
  // ── 즉시 (1~3일) ──
  {
    id: "death-certificate",
    category: "immediate",
    title: "사망진단서 발급",
    description: "병원 또는 담당 의사에게 사망진단서(시체검안서)를 발급받습니다.",
    where: "사망한 병원 또는 의원",
    documents: ["신분증"],
    tips: [
      "최소 10통 이상 발급받으세요. 은행, 보험사, 관공서마다 원본을 요구합니다.",
      "재발급은 병원에서 가능하며 1통당 1,000~2,000원입니다. 처음 받을 때 정확성을 꼭 확인하세요.",
    ],
    deadline: null,
    critical: true,
  },
  {
    id: "death-report",
    category: "immediate",
    title: "사망신고",
    description: "주민센터에 사망신고를 합니다. 사망일로부터 1개월 이내에 해야 합니다.",
    where: "주민센터 (사망지, 신고인 주소지, 고인 주소지 중 택1)",
    documents: [
      "사망진단서(시체검안서) 1통",
      "신고인 신분증",
    ],
    tips: [
      "사망신고 시 가족관계증명서에 사망 기록이 반영됩니다.",
      "사망신고 후 '안심상속 원스톱서비스'를 바로 신청할 수 있습니다.",
    ],
    deadline: 30,
    critical: true,
  },
  {
    id: "funeral",
    category: "immediate",
    title: "장례 진행",
    description: "장례식장 선정, 화장/매장 결정, 부고 연락 등 장례를 진행합니다.",
    where: "장례식장",
    documents: ["사망진단서"],
    tips: [
      "장례비용 영수증을 보관하세요. 상속세 공제 항목에 포함됩니다 (최소 500만원 공제, 직접비용 최대 1,000만원 한도, 봉안시설 별도 500만원 한도).",
      "화장의 경우 화장예약이 필요하며, 지역에 따라 대기가 있을 수 있습니다.",
    ],
    deadline: null,
    critical: false,
  },

  // ── 1주 이내 ──
  {
    id: "family-cert",
    category: "week1",
    title: "가족관계증명서 발급 (사망 기록 포함)",
    description: "사망신고 후 사망 기록이 반영된 가족관계증명서를 발급받습니다.",
    where: "주민센터, 대법원 전자가족관계등록시스템 (온라인)",
    documents: ["신청인 신분증"],
    tips: [
      "여러 통 발급받으세요. 은행, 보험사, 통신사 등 각 기관에 제출해야 합니다.",
      "온라인(efamily.scourt.go.kr)에서도 발급 가능합니다.",
    ],
    deadline: null,
    critical: true,
  },
  {
    id: "safe-inheritance",
    category: "week1",
    title: "안심상속 원스톱서비스 신청",
    description: "고인의 금융자산, 부동산, 자동차, 세금, 연금 등을 한번에 조회합니다.",
    where: "주민센터 또는 정부24 (online.gov.kr)",
    documents: [
      "신청인 신분증",
      "가족관계증명서",
    ],
    tips: [
      "사망일이 속한 달의 말일부터 1년 이내에 신청 가능합니다. 사망신고와 함께 바로 신청하는 것이 가장 좋습니다.",
      "결과는 항목별로 다릅니다 (일부 7일 이내, 금융·국세·연금 등은 20일 이내).",
      "숨은 보험, 예금, 대출 등이 있는지 확인하는 핵심 절차입니다.",
    ],
    deadline: 365,
    deadlineFromMonthEnd: true,
    critical: true,
  },
  {
    id: "find-insurance",
    category: "week1",
    title: "숨은 보험 조회",
    description: "고인 명의의 보험 가입 내역을 조회합니다.",
    where: "내보험찾아줌 (cont.insure.or.kr) 또는 생명보험협회/손해보험협회",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "신청인 신분증",
    ],
    tips: [
      "내보험찾아줌에서 생명·손해보험 통합 조회 가능합니다 (결과 확인은 협회별로 분리될 수 있음).",
      "⚠️ 망인 보험 조회는 안심상속 원스톱서비스 또는 상속인 금융거래조회 접수가 선행되어야 합니다.",
      "보험금 청구는 내보험찾아줌에서 불가하며, 각 보험사에 직접 청구해야 합니다.",
      "보험금 청구 시효는 상법상 3년이지만 빨리 확인하는 것이 좋습니다.",
    ],
    deadline: null,
    critical: true,
  },

  // ── 1개월 이내 ──
  {
    id: "bank-accounts",
    category: "month1",
    title: "은행 계좌 확인 및 정리",
    description: "각 은행에 방문하여 고인의 계좌를 확인하고 잔액 조회/해지/이전합니다.",
    where: "각 은행 영업점 (방문 필수)",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "상속인 전원의 인감증명서",
      "상속인 신분증",
      "상속협의서 (상속인이 여러 명인 경우)",
    ],
    tips: [
      "⚠️ 사망 전 인출하거나, 상속 절차 없이 인출하면 형사 처벌 대상이 될 수 있습니다.",
      "안심상속 원스톱서비스 결과를 받은 후 진행하는 것이 효율적입니다.",
      "은행마다 요구 서류가 다를 수 있으니 방문 전 전화 확인하세요.",
    ],
    deadline: null,
    critical: true,
  },
  {
    id: "insurance-claim",
    category: "month1",
    title: "보험금 청구",
    description: "조회된 보험에 대해 각 보험사에 보험금을 청구합니다.",
    where: "각 보험사 (온라인/방문/전화)",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "수익자 신분증",
      "수익자 통장 사본",
      "보험증권 (있는 경우)",
    ],
    tips: [
      "수익자가 지정되어 있으면 수익자가 청구합니다.",
      "수익자 미지정 시 법정상속인이 청구합니다.",
    ],
    deadline: null,
    critical: false,
  },
  {
    id: "telecom-cancel",
    category: "month1",
    title: "통신 서비스 해지",
    description: "고인의 휴대폰, 인터넷, IPTV 등 통신 서비스를 해지합니다.",
    where: "각 통신사 대리점 또는 고객센터",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "신청인 신분증",
    ],
    tips: [
      "사망 사유 해지 시 위약금 면제 약관이 있으나, 결합상품/지원금 등 예외가 있을 수 있으니 각 통신사에 확인하세요.",
      "⚠️ LG U+의 경우 명의변경 후 3개월 경과 조건이 있을 수 있으니 확인하세요.",
      "해지하지 않으면 요금이 계속 청구됩니다.",
    ],
    deadline: null,
    critical: false,
  },
  {
    id: "card-cancel",
    category: "month1",
    title: "카드 해지",
    description: "고인 명의의 신용카드/체크카드를 해지합니다.",
    where: "각 카드사 고객센터",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "신청인 신분증",
    ],
    tips: [
      "미결제 금액이 있으면 상속인에게 청구될 수 있습니다.",
      "자동결제가 연결된 카드는 먼저 자동결제를 해제하세요.",
    ],
    deadline: null,
    critical: false,
  },
  {
    id: "auto-payment",
    category: "month1",
    title: "자동이체/구독 서비스 정리",
    description: "공과금 자동이체, 구독 서비스(넷플릭스, 멜론, 쿠팡와우 등)를 해지합니다.",
    where: "각 서비스 고객센터 또는 앱",
    documents: [
      "사망진단서 (필요 시)",
      "가족관계증명서 (필요 시)",
    ],
    tips: [
      "고인의 휴대폰에 설치된 앱을 확인하면 구독 서비스를 파악할 수 있습니다.",
      "카드 명세서를 확인하면 자동결제 내역을 알 수 있습니다.",
    ],
    deadline: null,
    critical: false,
  },
  {
    id: "vehicle-transfer",
    category: "month6",
    title: "자동차 명의 이전",
    description: "고인 명의의 차량을 상속인 명의로 이전합니다.",
    where: "차량등록사업소",
    documents: [
      "상속협의서",
      "가족관계증명서",
      "상속인 신분증",
      "자동차등록증",
      "인감증명서",
    ],
    tips: [
      "사망일이 속한 달의 말일부터 6개월 이내에 이전해야 과태료(최대 50만원)가 발생하지 않습니다.",
      "자동차보험도 함께 변경해야 합니다.",
    ],
    deadline: 180,
    deadlineFromMonthEnd: true,
    critical: false,
  },

  // ── 3개월 이내 ──
  {
    id: "inheritance-decision",
    category: "month3",
    title: "상속 포기 / 한정승인 결정",
    description: "고인의 빚이 재산보다 많을 경우, 상속 포기 또는 한정승인을 법원에 신청합니다.",
    where: "가정법원",
    documents: [
      "상속포기/한정승인 심판청구서",
      "사망진단서",
      "가족관계증명서",
      "기본증명서",
      "주민등록등본",
    ],
    tips: [
      "⚠️ 상속개시 있음을 안 날로부터 3개월 이내에 반드시 신청해야 합니다.",
      "기한이 지나면 단순승인(모든 재산+빚 상속)으로 간주됩니다.",
      "한정승인은 재산 범위 내에서만 빚을 갚는 방식입니다.",
      "상속 포기는 취소할 수 없으니 신중하게 결정하세요.",
    ],
    deadline: 90,
    critical: true,
  },
  {
    id: "pension-survivor",
    category: "month1",
    title: "유족연금 / 반환일시금 신청",
    description: "국민연금 가입자 사망 시 유족연금 또는 반환일시금을 신청합니다.",
    where: "국민연금공단 지사 또는 온라인 (nps.or.kr)",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "신청인 신분증",
      "통장 사본",
    ],
    tips: [
      "유족연금 수급 요건(가입기간 등)을 확인하세요.",
      "유족연금과 반환일시금 중 유리한 것을 선택할 수 있습니다.",
      "법정 신청기한은 3개월이 아닙니다 (소멸시효: 급여 5년, 특정 반환일시금 10년). 다만 생활자금 공백 방지를 위해 빨리 신청하세요.",
    ],
    deadline: null,
    critical: false,
  },

  // ── 6개월 이내 ──
  {
    id: "inheritance-tax",
    category: "month6",
    title: "상속세 신고 및 납부",
    description: "상속재산이 일정 금액을 초과하면 상속세를 신고·납부해야 합니다.",
    where: "관할 세무서",
    documents: [
      "상속세 신고서",
      "상속재산 목록",
      "재산 감정평가서",
      "가족관계증명서",
      "금융거래 내역",
    ],
    tips: [
      "⚠️ 사망일이 속한 달의 말일부터 6개월 이내에 신고해야 합니다.",
      "기한 내 신고 시 신고세액공제 3%가 적용됩니다. 무신고 시 20~40% 가산세가 부과됩니다.",
      "상속공제(일괄공제 5억원, 배우자공제 등)를 확인하세요. 배우자공제를 받으려면 신고기한 후 6개월 내 재산분할(등기 포함) 필요.",
      "90% 이상이 세무사에게 위임합니다. 전문가 상담을 추천합니다.",
    ],
    deadline: 180,
    deadlineFromMonthEnd: true,
    critical: true,
  },
  {
    id: "property-registration",
    category: "month6",
    title: "부동산 상속등기",
    description: "고인 명의의 부동산을 상속인 명의로 등기 이전합니다.",
    where: "관할 등기소 또는 법무사",
    documents: [
      "등기신청서",
      "상속협의서 (상속인 전원 인감날인)",
      "인감증명서",
      "가족관계증명서",
      "취득세 납부 확인서",
      "부동산 등기부등본",
    ],
    tips: [
      "상속등기 자체에는 법적 기한이 없지만, 취득세 신고·납부 기한(말일 기준 6개월)은 별도로 존재합니다.",
      "⚠️ 상속 취득세는 사망일이 속한 달의 말일부터 6개월 이내에 신고·납부해야 합니다 (등기와 별개).",
      "미등기 상태에서 매매/담보 설정이 불가능합니다.",
      "취득세(농특세 포함)를 먼저 납부해야 등기 신청이 가능합니다.",
    ],
    deadline: null,
    critical: false,
  },

  // ── 이후 ──
  {
    id: "digital-accounts",
    category: "after",
    title: "디지털 계정 정리",
    description: "네이버, 카카오, 구글, SNS 등 고인의 디지털 계정을 정리합니다.",
    where: "각 서비스 고객센터/온라인",
    documents: [
      "사망진단서 (서비스에 따라 요구)",
      "가족관계증명서",
    ],
    tips: [
      "구글은 '비활성 계정 관리자' 기능으로 사전 설정이 가능합니다.",
      "카카오/네이버는 고객센터를 통해 계정 삭제를 요청할 수 있습니다.",
      "고인의 이메일에 중요한 정보(보험, 금융 등)가 있을 수 있으니 확인 후 정리하세요.",
    ],
    deadline: null,
    critical: false,
  },
  {
    id: "driver-license",
    category: "after",
    title: "운전면허 반납",
    description: "고인의 운전면허를 반납합니다.",
    where: "경찰서 또는 운전면허시험장",
    documents: [
      "사망진단서",
      "가족관계증명서",
      "운전면허증 (있는 경우)",
    ],
    tips: [
      "운전면허 반납은 의무는 아니지만, 신분증 도용 방지를 위해 권장됩니다.",
    ],
    deadline: null,
    critical: false,
  },
];
